"use client";

import { useState } from "react";
import { DndContext, DragEndEvent, DragOverlay, PointerSensor, useDraggable, useDroppable, useSensor, useSensors } from "@dnd-kit/core";
import { BriefcaseBusiness, ChevronDown, MoreHorizontal, Plus, Users } from "lucide-react";
import { candidates, type Candidate } from "@/components/dashboard/data";

const columns = ["Applied", "Screened", "Interview", "Offer", "Rejected"];
function Card({ candidate }: { candidate: Candidate }) { const { attributes, listeners, setNodeRef, transform } = useDraggable({ id: candidate.name }); return <article ref={setNodeRef} {...listeners} {...attributes} className="kanban-card" style={transform ? { transform: `translate3d(${transform.x}px, ${transform.y}px, 0)` } : undefined}><div className="kanban-card-top"><div className="candidate-avatar" style={{ background: candidate.color }}>{candidate.initials}</div><button><MoreHorizontal size={16} /></button></div><strong>{candidate.name}</strong><small>{candidate.role}</small><div className="kanban-card-footer"><span className="kanban-score">{candidate.score}% match</span><span>{candidate.location === 'Remote' ? 'Remote' : candidate.location.split(',')[0]}</span></div></article>; }
function Column({ title, items }: { title: string; items: Candidate[] }) { const { setNodeRef, isOver } = useDroppable({ id: title }); return <section ref={setNodeRef} className={`kanban-column ${isOver ? 'column-over' : ''}`}><header><div><h2>{title}</h2><span>{items.length}</span></div><button><Plus size={15} /></button></header><div className="kanban-items">{items.map((candidate) => <Card candidate={candidate} key={candidate.name} />)}</div></section>; }
export default function PipelinePage() { const [items, setItems] = useState<Record<string, Candidate[]>>(() => Object.fromEntries(columns.map((column) => [column, candidates.filter((candidate) => candidate.stage === column)]))); const sensors = useSensors(useSensor(PointerSensor, { activationConstraint: { distance: 6 } })); const move = ({ active, over }: DragEndEvent) => { if (!over || active.id === over.id || !columns.includes(String(over.id))) return; const candidate = Object.values(items).flat().find((item) => item.name === active.id); if (!candidate) return; setItems((current) => Object.fromEntries(columns.map((column) => [column, column === over.id ? [...current[column], candidate] : current[column].filter((item) => item.name !== candidate.name)]))); }; return <main className="pipeline-page"><header className="pipeline-header"><div><p className="eyebrow">RECRUITING WORKSPACE</p><h1>Candidate pipeline</h1><p>Move candidates through your process as decisions get made.</p></div><button className="primary-button"><Plus size={16} /> Add candidate</button></header><div className="pipeline-toolbar"><div className="job-selector"><div className="job-dot" /><span>Senior Product Designer</span><ChevronDown size={15} /></div><span className="pipeline-meta"><BriefcaseBusiness size={14} /> 24 candidates <Users size={14} /> 3 reviewers</span></div><DndContext sensors={sensors} onDragEnd={move}><div className="kanban-board">{columns.map((column) => <Column title={column} items={items[column]} key={column} />)}</div><DragOverlay /></DndContext></main>; }
