"use client";

import { ChevronDown, ChevronRight, Filter, MoreHorizontal, Search } from "lucide-react";
import type { Candidate } from "./data";

const stages = ["All candidates", "Applied", "Screened", "Interview", "Offer", "Rejected"];

export function CandidatePipeline({ candidates, selected, stage, onSelect, onStageChange }: { candidates: readonly Candidate[]; selected: Candidate; stage: string; onSelect: (candidate: Candidate) => void; onStageChange: (stage: string) => void }) {
  const visibleCandidates = candidates.filter((candidate) => stage === "All candidates" || candidate.stage === stage);
  return <><section className="section-header"><div><h2>Candidate pipeline</h2><p>Review and move candidates through your active roles.</p></div><button className="view-link">View pipeline <ChevronRight size={15} /></button></section><section className="toolbar"><div className="job-selector"><div className="job-dot" /><span>Senior Product Designer</span><ChevronDown size={15} /></div><div className="toolbar-right"><div className="search-box"><Search size={16} /><input placeholder="Search candidates" /></div><button className="filter-button"><Filter size={15} /> Filters <span>2</span></button></div></section><div className="stage-tabs">{stages.map((item) => <button onClick={() => onStageChange(item)} className={stage === item ? "selected" : ""} key={item}>{item}{item === "All candidates" && <span>24</span>}</button>)}</div><section className="candidate-table"><div className="table-head"><span>Candidate</span><span>Match score</span><span>Stage</span><span>Location</span><span>Applied</span><span /></div>{visibleCandidates.map((candidate) => <button className={`candidate-row ${selected.name === candidate.name ? "row-selected" : ""}`} onClick={() => onSelect(candidate)} key={candidate.name}><div className="candidate-cell"><div className="candidate-avatar" style={{ background: candidate.color }}>{candidate.initials}</div><div><strong>{candidate.name}</strong><small>{candidate.role}</small></div></div><div className={`score ${candidate.score >= 90 ? "high" : ""}`}><div className="score-track"><i style={{ width: `${candidate.score}%` }} /></div><strong>{candidate.score}%</strong></div><div><span className={`stage-pill ${candidate.stage.toLowerCase()}`}>{candidate.stage}</span></div><span className="muted-cell">{candidate.location}</span><span className="muted-cell">{candidate.applied}</span><MoreHorizontal size={18} className="row-more" /></button>)}</section><p className="table-footer">Showing {visibleCandidates.length} of 24 candidates <button>Load more</button></p></>;
}

export function Stat({ label, value, detail, trend, icon }: { label: string; value: string; detail: string; trend: string; icon: React.ReactNode }) { return <div className="stat-card"><div className="stat-top"><span>{label}</span><div className="stat-icon">{icon}</div></div><div className="stat-value">{value} {trend && <small>{trend}</small>}</div><p>{detail}</p></div>; }
